# Generated by Django 2.2.3 on 2019-07-22 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atualizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=32)),
                ('data', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('disp', models.IntegerField(default=0)),
                ('resv', models.IntegerField(default=0)),
                ('ultimo_estoque', models.IntegerField(default=-1)),
                ('estoque_last_updated', models.DateField()),
                ('nome', models.CharField(max_length=120)),
                ('cx', models.IntegerField(default=0)),
                ('inativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Incluido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_incluidos', to='fichas.Produto')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
