# Generated by Django 2.2.3 on 2019-07-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque_last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
