# Generated by Django 2.2.3 on 2020-01-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_auto_20190806_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cv',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
