# Generated by Django 2.2.3 on 2019-07-22 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('empresa_numero', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=200)),
                ('data', models.DateField()),
            ],
            options={
                'ordering': ['empresa_numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimento_itempedidos', to='movimento.Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimento_itempedidos', to='fichas.Produto')),
            ],
            options={
                'ordering': ['pedido', 'produto'],
                'unique_together': {('pedido', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('container', models.CharField(max_length=60)),
                ('qtde', models.IntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimento_compras', to='fichas.Produto')),
            ],
            options={
                'ordering': ['-container', 'produto'],
                'unique_together': {('container', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='Chegando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('qtde', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimento_chegandos', to='fichas.Produto')),
            ],
            options={
                'ordering': ['produto', 'nome'],
                'unique_together': {('produto', 'nome')},
            },
        ),
    ]
