# Generated by Django 2.2.3 on 2019-08-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_auto_20190806_1055'),
        ('movimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chegando',
            options={'ordering': ['produto', 'nome', 'qtde']},
        ),
        migrations.AlterUniqueTogether(
            name='chegando',
            unique_together={('produto', 'nome', 'qtde')},
        ),
    ]
