# Generated by Django 2.2.3 on 2020-01-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0002_auto_20190812_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-data', 'produto']},
        ),
    ]
